spring:
  datasource:
    url: jdbc:mysql://localhost:3306/password_reset?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate.ddl-auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.show_sql: true
  messages:
    basename: base
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectionTimeout: 30000
      mail.smtp.timeout: 30000
      mail.smtp.protocol: smtp
      mail.smtp.test-connection: false
